# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

autoscaling:
  enabled: true
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80 # The CPU utilization percentage threshold for the autoscaler expressed as % of the cpu request

image:
  # repository: PLACEHOLDER
  tag: APP_VERSION
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

readinessProbePath: "/health/readiness"
livenessProbePath: "/health/check"

service:
  type: ClusterIP
  port: 80                    # This is then inbound port from the LB
  targetPort: 8080            # This is the port your app runs on

# enable this if your app uses google endpoints for authentication.
googleEndpoints:
  enabled: false
  targetPort: 8081  # This is the port that google endpoints will listen to

# enable this to add a cloudsql proxy sidecar container to your deployment
cloudsql:
  enabled: false
  instances: []     # the cloudsql proxy can proxy multiple instances at once on different ports. Pass an array containing the instance 
    # - connectionName: "project:us-central1:instance" #this is the connection name for the instance
    #   port: 3306                                     # the port on which the cloudsql proxy will expose this particular instance

ingress:
  enabled: true
  sessionAffinity: false

  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-cluster-issuer

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 2000m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
