
{{- $targetPort := .Values.service.targetPort -}}
{{- if .Values.googleEndpoints.enabled -}}
{{- $targetPort = .Values.googleEndpoints.targetPort -}}
{{- end -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "growth-partners-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "growth-partners-api.name" . }}
    helm.sh/chart: {{ include "growth-partners-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ include "growth-partners-api.name" . }}
    chart: {{ include "growth-partners-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ $targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "growth-partners-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ include "growth-partners-api.name" . }}
    release: {{ .Release.Name }}
